version: '3'
services:
  ai-interview:
    build: .
    volumes:
      - .:/app  # Mount the current directory (project) to the /app directory in the container
    ports:
      - "8080:8080"  # Expose port 8080 on the container to port 8080 on the host
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development  # Set Flask to development mode for debugging
    command: flask run --host=0.0.0.0 --port=8080
