
services:
  ai-interview:
    build: .
    container_name: ai-interview-dev
    volumes:
      - .:/app  
      - app-data:/app/data  
    ports:
      - "8080:8080"  
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development  
    command: flask run --host=0.0.0.0 --port=8080 --debugger --reload
    develop:
      watch:
        - action: sync 
          path: ./app 
          target: /app 
          ignore:
            - __pycache__/  
            - recorded_audio/  
            - recorded_video/
            - tmp/
        - action: rebuild  
          path: requirements.txt

volumes:
  dpu-backend: 
    external: true
  app-data:  
    driver: local


